name: DSformer
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bibtexparser=1.4.3=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py311h7c6b74e_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py311hdf67eae_3
  - cpython=3.11.14=py311hd8ed1ab_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - expat=2.7.3=h3385a95_0
  - fonttools=4.60.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - future=1.0.0=pyhd8ed1ab_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libdeflate=1.22=hb9d3cd8_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h4751f2c_7
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libnsl=2.0.0=h5eee18b_0
  - libpng=1.6.50=h421ea60_1
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.0=he137b08_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb25bd0a_0
  - lxml=6.0.2=py311hc53b721_0
  - matplotlib-base=3.10.7=py311h0f3be63_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py311hacdc0fc_0
  - mkl_fft=2.1.1=py311h8fe796d_0
  - mkl_random=1.3.0=py311h505adc9_0
  - monty=2025.3.3=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.10.2=pyhcf101f3_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.5=pyhe01879c_0
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.6.0=h26f9b46_0
  - orjson=3.11.4=py311h902ca64_0
  - packaging=25.0=pyh29332c3_1
  - palettable=3.3.3=pyhd8ed1ab_1
  - pandas=2.3.3=py311hed34c8f_1
  - pip=25.2=pyhc872135_1
  - plotly=6.4.0=pyhd8ed1ab_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybtex=0.25.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pymatgen=2025.10.7=py311h0372a8f_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3778330_0
  - qhull=2020.2=h434a139_5
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - ruamel.yaml=0.18.16=py311h49ec1c0_0
  - ruamel.yaml.clib=0.2.14=py311h49ec1c0_0
  - scipy=1.16.3=py311h33bc11c_0
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - spglib=2.6.0=py311h9f68a5c_1
  - sqlite=3.51.0=h2a70700_0
  - sympy=1.14.0=pyh2585a3b_105
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=py311h92b7b1e_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - uncertainties=3.2.3=pyhd8ed1ab_0
  - unicodedata2=17.0.0=py311h49ec1c0_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.25.0=py311haee01d2_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - cupy-cuda12x==13.6.0
      - fastrlock==0.8.3
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - grpcio==1.76.0
      - jarvis-tools==2025.5.30
      - jinja2==3.1.6
      - lightning-utilities==0.15.2
      - markdown==3.10
      - markupsafe==3.0.3
      - multidict==6.7.0
      - numpy==1.26.4
      - pillow==12.0.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - pyg-lib==0.4.0+pt21cu121
      - pytorch-lightning==2.1.3
      - pytorch-pfn-extras==0.8.4
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - torch==2.1.1+cu121
      - torch-cluster==1.6.3+pt21cu121
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt21cu121
      - torch-sparse==0.6.18+pt21cu121
      - torch-spline-conv==1.2.2+pt21cu121
      - torchmetrics==1.8.2
      - triton==2.1.0
      - werkzeug==3.1.3
      - xmltodict==1.0.2
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/cj/.conda/envs/DSformer
